# Generated by Django 3.2.18 on 2023-09-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230917_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.CharField(default='24', max_length=20),
        ),
    ]
