# Generated by Django 3.2.18 on 2023-09-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dept',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
